MAX_ENEMIES = 6
HAND_SIZE   = 10
MAX_POTIONS = 9
MAX_CHOICES = 10

CARD_ACTIONS   = HAND_SIZE * MAX_ENEMIES
POTION_ACTIONS = MAX_POTIONS * MAX_ENEMIES
CHOICE_ACTIONS = MAX_CHOICES
END_TURN       = CARD_ACTIONS + POTION_ACTIONS + CHOICE_ACTIONS + 1